#! /bin/sh

case "$1" in
  start)
        start-stop-daemon --start --pidfile /var/run/reflexfps.pid -m -c admin -b --exec /usr/bin/wine /home/admin/steamcmd/reflexfps/reflexded.exe
    ;;
  stop)
    ;;

  restart)
    ;;

  *)
    echo "Usage: /etc/init.d/reflexfps {start|stop|restart}"
    exit 1
esac

exit 0